/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/$notFound'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthBlogRouteImport } from './routes/_auth/blog'
import { Route as Auth_dashboardAdminRouteImport } from './routes/_auth/__dashboard/admin'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/$notFound',
  path: '/$notFound',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBlogRoute = AuthBlogRouteImport.update({
  id: '/_auth/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_dashboardAdminRoute = Auth_dashboardAdminRouteImport.update({
  id: '/_auth/__dashboard/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$notFound': typeof NotFoundRoute
  '/blog': typeof AuthBlogRoute
  '/login': typeof AuthLoginRoute
  '/admin': typeof Auth_dashboardAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$notFound': typeof NotFoundRoute
  '/blog': typeof AuthBlogRoute
  '/login': typeof AuthLoginRoute
  '/admin': typeof Auth_dashboardAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$notFound': typeof NotFoundRoute
  '/_auth/blog': typeof AuthBlogRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/__dashboard/admin': typeof Auth_dashboardAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$notFound' | '/blog' | '/login' | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$notFound' | '/blog' | '/login' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$notFound'
    | '/_auth/blog'
    | '/_auth/login'
    | '/_auth/__dashboard/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundRoute: typeof NotFoundRoute
  AuthBlogRoute: typeof AuthBlogRoute
  AuthLoginRoute: typeof AuthLoginRoute
  Auth_dashboardAdminRoute: typeof Auth_dashboardAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$notFound': {
      id: '/$notFound'
      path: '/$notFound'
      fullPath: '/$notFound'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/blog': {
      id: '/_auth/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AuthBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/__dashboard/admin': {
      id: '/_auth/__dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Auth_dashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundRoute: NotFoundRoute,
  AuthBlogRoute: AuthBlogRoute,
  AuthLoginRoute: AuthLoginRoute,
  Auth_dashboardAdminRoute: Auth_dashboardAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
