import { IApp } from "@/shared/types/IApp";
import {
  Briefcase,
  Music,
  Camera,
  MessageCircle,
  Calendar,
  CloudRain,
  ShoppingBag,
  Heart,
  Calculator,
  PenIcon,
  HelpingHand,
  Map,
  Settings,
  Smartphone,
  TrendingUp,
} from "lucide-react";

export const apps: IApp[] = [
  {
    id: "kjobs",
    name: "KJobs",
    description: "Professional career platform with AI-powered job matching",
    price: "Free",
    icon: Briefcase,
    color: "from-blue-500 to-blue-700",
    category: "productivity",
    url: "/jobs", // Internal route
    rating: 4.8,
    badge: "Popular",
    features: ["AI Matching", "Resume Builder", "Career Insights"],
    isInternal: true,
  },
  {
    id: "kmusic",
    name: "KMusic Studio",
    description: "Professional audio experience with spatial sound",
    price: "$9.99/month",
    originalPrice: "$14.99",
    icon: Music,
    color: "from-red-500 to-pink-600",
    category: "entertainment",
    url: "https://music.apple.com",
    rating: 4.8,
    badge: "Editor's Choice",
    features: ["Spatial Audio", "Offline Mode", "High Quality"],
  },
  {
    id: "kphotos",
    name: "KPhoto Pro",
    description: "AI-powered photo editing and cloud storage",
    price: "Free",
    icon: Camera,
    color: "from-blue-500 to-cyan-500",
    category: "productivity",
    url: "https://www.icloud.com/photos",
    rating: 4.9,
    badge: "New",
    features: ["AI Enhancement", "Cloud Sync", "RAW Support"],
  },
  {
    id: "kmessages",
    name: "KConnect",
    description: "Secure messaging with end-to-end encryption",
    price: "Free",
    icon: MessageCircle,
    color: "from-green-500 to-emerald-500",
    category: "communication",
    url: "https://messages.google.com",
    rating: 4.7,
    features: ["E2E Encryption", "Group Chat", "File Sharing"],
    badge: "Popular",
  },
  {
    id: "kcalendar",
    name: "KSchedule Pro",
    description: "Smart calendar with AI scheduling assistant",
    price: "$4.99/month",
    originalPrice: "$9.99",
    icon: Calendar,
    color: "from-orange-500 to-red-500",
    category: "productivity",
    url: "https://calendar.google.com",
    rating: 4.6,
    badge: "Trending",
    features: ["AI Assistant", "Team Sync", "Smart Reminders"],
  },
  {
    id: "kweather",
    name: "KWeather Plus",
    description: "Hyperlocal weather with beautiful visualizations",
    price: "Free",
    icon: CloudRain,
    color: "from-blue-400 to-blue-600",
    category: "utilities",
    url: "https://weather.com",
    rating: 4.5,
    features: ["Hyperlocal", "Radar Maps", "Alerts"],
    badge: "Popular",
  },
  {
    id: "kshopping",
    name: "KShop Smart",
    description: "AI-powered shopping with price comparison",
    price: "Free",
    icon: ShoppingBag,
    color: "from-purple-500 to-pink-500",
    category: "lifestyle",
    url: "https://www.amazon.com",
    rating: 4.4,
    features: ["Price Alerts", "Wish Lists", "Reviews"],
    badge: "Popular",
  },
  {
    id: "kmaps",
    name: "KNavigate",
    description: "Advanced navigation with real-time traffic",
    price: "Free",
    icon: Map,
    color: "from-green-400 to-blue-500",
    category: "utilities",
    url: "https://maps.google.com",
    rating: 4.8,
    features: ["Live Traffic", "Offline Maps", "AR View"],
    badge: "Popular",
  },
  {
    id: "khealth",
    name: "KWellness",
    description: "Complete health tracking and fitness coaching",
    price: "$6.99/month",
    icon: Heart,
    color: "from-red-400 to-pink-500",
    category: "lifestyle",
    url: "https://www.fitbit.com",
    rating: 4.7,
    features: ["Health Tracking", "AI Coach", "Social Features"],
    badge: "Popular",
  },
  {
    id: "kcalculator",
    name: "KCalc Pro",
    description: "Advanced calculator with scientific functions",
    price: "$2.99",
    icon: Calculator,
    color: "from-gray-600 to-gray-800",
    category: "utilities",
    url: "https://calculator.net",
    rating: 4.3,
    features: ["Scientific", "Graphing", "History"],
    badge: "Popular",
  },
  {
    id: "kBlog",
    name: "K Blog",
    description: "Read Latest Articales On Intreasting Topics ",
    price: "Free",
    icon: PenIcon,
    color: "from-gray-600 to-gray-800",
    category: "utilities",
    url: "/blogs",
    rating: 4.3,
    features: ["Scientific", "Graphing", "History"],
    badge: "Popular",
  },
  {
    id: "kMentor",
    name: "K Mentor",
    description: "Get Guidence From Mentors Around the World",
    price: "Free",
    icon: HelpingHand,
    color: "from-gray-600 to-green-800",
    category: "utilities",
    url: "/kmentor",
    rating: 4.3,
    features: ["Scientific", "Graphing", "History"],
    badge: "Popular",
  },
];

export const categories = [
  { id: "all", name: "All Apps", icon: Smartphone },
  { id: "productivity", name: "Productivity", icon: TrendingUp },
  { id: "entertainment", name: "Entertainment", icon: Music },
  { id: "communication", name: "Communication", icon: MessageCircle },
  { id: "utilities", name: "Utilities", icon: Settings },
  { id: "lifestyle", name: "Lifestyle", icon: Heart },
];
