/// <reference types="vite/client" />
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// If you have a types file, import Database type, otherwise remove the next line
// import type { Database } from './types';

// Get environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_DEV_URL!;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY!;

// Validate variables
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error('Missing Supabase environment variables');
}

// Create and export Supabase client
// If you have a Database type, use it as a generic, otherwise just use createClient
// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
