// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjubucmfgpcvcuqibofk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqdWJ1Y21mZ3BjdmN1cWlib2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTQ1MTAsImV4cCI6MjA1OTk3MDUxMH0.oCDbz7LN--Xci6ZgZLdd7q4fI_sPczYUC8HXSDOb3ZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);